name: CustomItemProvider
version: ${project.version}
main: net.cloudlite.plugin.PluginAddon
api-version: "1.16"
authors: [DaltonBurchard]
description: Adds functionality for ShopGUI+ to sell/buy CustomItems items!
depend: ["ShopGUIPlus"]
